//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_FinalDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tOrder
    {
        public int Id { get; set; }

        [DisplayName("編號")]
        public string fOrderID { get; set; }

        [DisplayName("訂購人")]
        public string fCustomerName { get; set; }

        [DisplayName("連絡電話")]
        public string fCustomerPhone { get; set; }

        [DisplayName("信箱")]
        public string fCustomerEmail { get; set; }

        [DisplayName("日期")]
        public string fDate { get; set; }

        [DisplayName("狀態")]
        public string fState { get; set; }
    }
}
